# -*- coding: UTF-8 -*-
lista = [50, 70, 80, 40, 10, 30, 20, 30]
print 'Coordenada 1:', lista[1]
print 'Elementos dos índices de 1 a 4:', lista[1:5]
print 'Elementos até o índice 4:', lista[:5]
print 'Elementos a partir do índice 5:', lista[5:]
print '5 últimos elementos', lista[-5:]
print 'Começando no índice 1, de 2 em 2:', lista[1::2]
print 'Elementos de índice par', lista [::2]
print 'Elementos de índice ímpar', lista[1::2]